name: totodo
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  awesome_notifications: ^0.0.5+8
  carousel_slider: ^1.4.1
  charter: ^0.0.1-alpha-3
  modern_charts: ^0.1.19
  cupertino_icons: ^0.1.2
  fl_chart: ^0.20.1
  percent_indicator: ^2.1.7+2
  dio: 3.0.9
  easy_debounce: ^1.0.2
  firebase_auth: ^0.15.0+1
  firebase_core: ^0.4.0+8
  flutter_facebook_login: ^3.0.0
  flutter_icons: ^1.1.0
  flutter_local_notifications: ^4.0.1+2
  flutter_native_timezone: ^1.0.10
  flutter_reorderable_list: ^0.1.5
  flutter_svg: ^0.21.0-nullsafety.0
  freezed: ^0.10.6
  freezed_annotation: null
  get_it: ^5.0.1
  giffy_dialog: ^1.8.0
  google_sign_in: ^4.0.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  http: ^0.12.2
  injectable: ^1.0.5
  intl: ^0.17.0
  json_annotation: any
  keyboard_visibility: ^0.5.6
  logger: ^0.9.4
  path_provider: ^1.6.27
  provider: ^4.3.2+2
  retrofit: any
  rxdart: ^0.23.1
  shared_preferences: ^0.5.6+3
  shimmer: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  build_runner: null
  # Data
  equatable: ^2.0.0-nullsafety

  # Bloc
  flutter_bloc: ^6.1.2
  # Generator
  hive_generator: ^0.8.2
  injectable_generator: ^1.0.4
  json_serializable: any

  # Lint
  lint: ^1.1.1
  meta: ^1.1.6
  retrofit_generator: any

  # Unit test
  test: null
  uuid: 2.0.1

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.otf
          weight: 400
        - asset: fonts/Poppins-Medium.otf
          weight: 500
        - asset: fonts/Poppins-SemiBold.otf
          weight: 600
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
          weight: 400

  assets:
    - assets/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
