name: totodo
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Notification
  awesome_notifications: ^0.0.5+8

  # UI
  keep_keyboard_popup_menu: ^2.0.3
  carousel_slider: ^1.4.1

  # Chart
  charter: ^0.0.1-alpha-3
  modern_charts: ^0.1.19
  fl_chart: ^0.20.1
  percent_indicator: ^2.1.7+2
  charts_flutter: ^0.10.0

  cupertino_icons: ^0.1.2
  dio: 3.0.9
  easy_debounce: ^1.0.2
  firebase_auth: ^0.15.0+1
  firebase_core: ^0.4.0+8
  flutter_facebook_login: ^3.0.0
  flutter_icons: ^1.1.0
  flutter_colorpicker: ^0.4.0
  # Notification
  flutter_local_notifications: ^4.0.1+2
  flutter_native_timezone: ^1.0.10
  flutter_reorderable_list: ^0.1.5
  flutter_svg: ^0.21.0-nullsafety.0
#  freezed: ^0.10.6
#  freezed_annotation: null
  get_it: ^6.0.0
  giffy_dialog: ^1.8.0
  google_sign_in: ^4.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  http: ^0.12.2
  injectable: ^1.2.0
  intl: ^0.17.0
  json_annotation: any
  keyboard_visibility: ^0.5.6
  logger: ^0.9.4
  path_provider: ^2.0.0
  provider: ^4.3.2+2
  retrofit: any
  rxdart: ^0.23.1
  shared_preferences: ^0.5.6+3
  shimmer: ^1.1.1
  slide_to_confirm: ^0.0.7
  table_calendar: ^3.0.0
  build: ^1.5.2
  analyzer: ^1.1.0
  workmanager: ^0.4.0
  connectivity: ^3.0.6
  pull_to_refresh: ^2.0.0
  cached_network_image: ^2.5.1
  flutter_cache_manager: ^2.1.0

  # Cron
  cronparse: ^0.1.1

  # Image picker
  image_picker: 0.6.7+21

dev_dependencies:
  flutter_test:
    sdk: flutter
#  bloc_test: ^7.1.0
  build_runner: ^1.11.5
  # Data
  equatable: ^2.0.0-nullsafety

  # Bloc
  flutter_bloc: ^6.1.2
  # Generator
  hive_generator: ^1.0.0
  injectable_generator: ^1.2.0
  json_serializable: any

  # Lint
  lint: ^1.1.1
  meta: ^1.1.6
  retrofit_generator: any

  mockito: ^4.1.1

  objectid: ^2.0.0
  # Unit test
  test: null

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 500
        - asset: fonts/OpenSans-Bold.ttf
          weight: 600
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
          weight: 400

  assets:
    - assets/
    - assets/habit/
    - assets/emotional/
    - assets/Habit Icons/
    - assets/Habit Checkin Imgs/