name: totodo
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  retrofit: any
  json_annotation: any
  carousel_slider: ^1.4.1
  # DI
  get_it: ^5.0.1
  injectable: ^1.0.5
  #object builder
  freezed: ^0.10.6

  #format date time and other formats
  intl: ^0.16.1

  # local storage
  shared_preferences: ^0.5.6+3
  freezed_annotation:
dev_dependencies:
  flutter_test:
    sdk: flutter
  # Data
  equatable: ^0.6.0
  meta: ^1.1.6
  sprintf: "^4.0.0"
  uuid: "2.0.1"
  # UI
  flutter_svg: ^0.18.1
  dotted_border: ^1.0.4
  shimmer: ^1.1.1
  # Provider
  provider: ^4.3.2+2
  # Bloc
  flutter_bloc: ^3.1.0
  dio: 3.0.9
  retrofit_generator: any
  json_serializable: any
  # Lint
  lint: ^1.1.1
  injectable_generator: ^1.0.4
  # Auth
  firebase_core: ^0.4.0+8
  google_sign_in: ^4.0.0
  firebase_auth: ^0.15.0+1
  # Unit test
  test:
  bloc_test: ^4.0.0
  build_runner:
  freezed:

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.otf
          weight: 400
        - asset: fonts/Poppins-Medium.otf
          weight: 500
        - asset: fonts/Poppins-SemiBold.otf
          weight: 600
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
          weight: 400

  assets:
    - assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
